In [30]:
from sklearn.model_selection import train_test_split, cross_val_predict, KFold
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error, roc_auc_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score
from sklearn.metrics import confusion_matrix
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, StandardScaler, MinMaxScaler
from sklearn.impute import SimpleImputer
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from plotly.subplots import make_subplots
import plotly.graph_objs as go
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.metrics import roc_auc_score, make_scorer
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import RandomizedSearchCV
import shap
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
from sklearn.model_selection import StratifiedKFold, cross_validate
import plotly.express as px
from catboost import CatBoostRegressor
from sklearn.dummy import DummyRegressor
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from catboost import CatBoostRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

In [2]:
RANDOM_STATE = 12345

In [3]:
df = pd.read_csv("../data/diamonds.csv")

In [4]:
X = df.drop('price', axis = 1)

In [5]:
y = df['price']

In [6]:
X.head()

   Unnamed: 0  carat      cut color clarity  depth  table     x     y     z
0           1   0.23    Ideal     E     SI2   61.5   55.0  3.95  3.98  2.43
1           2   0.21  Premium     E     SI1   59.8   61.0  3.89  3.84  2.31
2           3   0.23     Good     E     VS1   56.9   65.0  4.05  4.07  2.31
3           4   0.29  Premium     I     VS2   62.4   58.0  4.20  4.23  2.63
4           5   0.31     Good     J     SI2   63.3   58.0  4.34  4.35  2.75

In [9]:
X = X.drop(columns = 'Unnamed: 0')

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = RANDOM_STATE)

In [11]:
X_train.shape

(43152, 9)

In [12]:
num_cols = X_train.select_dtypes(include='number').columns.tolist()

In [13]:
cat_cols = X_train.select_dtypes(include='object').columns.tolist()

/var/folders/jt/pfrf2kqn59d1ph0418pyq4mr0000gn/T/ipykernel_9488/4180746908.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = X_train.select_dtypes(include='object').columns.tolist()

In [14]:
numeric_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="median"))
])

categorical_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer([
    ("num", numeric_transformer, num_cols),
    ("cat", categorical_transformer, cat_cols)
])

In [22]:
models = {
    "Dummy Regressor": DummyRegressor(strategy="mean"),

    "Linear Regression": LinearRegression(),

    "Decision Tree": DecisionTreeRegressor(
        random_state=RANDOM_STATE
    ),

    "Random Forest": RandomForestRegressor(
        n_estimators=200,
        random_state=RANDOM_STATE,
        n_jobs=-1
    ),

    "CatBoost": CatBoostRegressor(
        iterations=300,
        depth=6,
        learning_rate=0.1,
        verbose=0,
        random_state=RANDOM_STATE
    )
}

In [25]:
cv = KFold(
    n_splits=5,
    shuffle=True,
    random_state=RANDOM_STATE
)

scoring = {
    "mae": "neg_mean_absolute_error",
    "rmse": "neg_root_mean_squared_error",
    "r2": "r2"
}

baseline_results = []

for model_name, model in models.items():
    pipeline = Pipeline([
        ("preprocessor", preprocessor),
        ("model", model)
    ])

    scores = cross_validate(
        pipeline,
        X_train,
        y_train,
        cv=cv,
        scoring=scoring,
        n_jobs=-1
    )

    baseline_results.append({
        "model": model_name,
        "mae_mean": -scores["test_mae"].mean(),
        "mae_std": scores["test_mae"].std(),
        "rmse_mean": -scores["test_rmse"].mean(),
        "rmse_std": scores["test_rmse"].std(),
        "r2_mean": scores["test_r2"].mean(),
        "r2_std": scores["test_r2"].std()
    })

baseline_results = (
    pd.DataFrame(baseline_results)
    .sort_values("rmse_mean")
    .reset_index(drop=True)
)

baseline_results

,model,mae_mean,mae_std,rmse_mean,rmse_std,r2_mean,r2_std
0,Random Forest,276.889439,3.601174,560.114118,7.423142,0.980364,0.000595
1,CatBoost,302.924809,3.667968,561.136221,7.735026,0.980280,0.000943
2,Decision Tree,369.485857,4.686862,760.495468,10.823552,0.963808,0.000876
3,Linear Regression,747.567702,4.810565,1140.687293,18.802902,0.918543,0.003218
4,Dummy Regressor,3041.388434,25.462355,3998.878075,55.919183,-0.000381,0.000263

In [27]:
best_model_name = baseline_results.loc[0, "model"]
best_model_name

best_model = models[best_model_name]

best_baseline_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", best_model)
])

best_baseline_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median'))]),
                                                  ['carat', 'depth', 'table',
                                                   'x', 'y', 'z']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['cut', 'color',
                                                   'clarity'])])),
                ('model',
                 RandomForestRegressor(n_estimators=200, n_jobs=-1,
                                       random_state=12345))])

In [31]:
y_pred = best_baseline_pipeline.predict(X_test)

test_metrics = {
    "mae": mean_absolute_error(y_test, y_pred),
    "rmse": np.sqrt(mean_squared_error(y_test, y_pred, )),
    "r2": r2_score(y_test, y_pred)
}

test_metrics_df = pd.DataFrame([test_metrics])

display(test_metrics_df)

          mae        rmse        r2
0  266.601151  542.163799  0.981166

In [34]:
predictions_df = pd.DataFrame({
    "y_true": y_test,
    "y_pred": y_pred
})

predictions_df["error"] = (
    predictions_df["y_true"] - predictions_df["y_pred"]
)

display(predictions_df.head())

       y_true    y_pred    error
5246     3789  4215.465 -426.465
12373     597   617.765  -20.765
40394    1133  1004.570  128.430
20235    8666  8436.375  229.625
45892    1720  1692.265   27.735

In [37]:
px.histogram(
    predictions_df,
    x="error",
    nbins=50,
    title="Распределение ошибок модели",
    labels={"error": "Ошибка прогноза"}
)

In [38]:
px.scatter(
    predictions_df.sample(5000, random_state=42),
    x="y_true",
    y="y_pred",
    opacity=0.5,
    title="Сравнение фактических и предсказанных значений",
    labels={
        "y_true": "Фактическая цена",
        "y_pred": "Предсказанная цена"
    }
)

Случайный лес оказался лучшей моделью с mae_mean 276.889439 и r2 0.980364